---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/users: {{ toJson .Values.users | sha256sum }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: bastion
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag $ }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -ec
            - |
              cd /etc/ssh
              for ssh_key in /etc/ssh/ssh_host_*_key; do
                if [ ! -f ${ssh_key}.pub ]; then
                  ssh-keygen -y -f ${ssh_key} > ${ssh_key}.pub
                fi
              done

              USER_UID=1000
              for i in /etc/users/*; do
                useradd -rm -d /home/${i##*/} -s /bin/bash -g root -u $((USER_UID++)) ${i##*/}
                mkdir -p /home/${i##*/}/.ssh
                install -Dm0600 $i /home/${i##*/}/.ssh/authorized_keys
                chmod 700 /home/${i##*/}/.ssh
                chown -R ${i##*/}:nogroup /home/${i##*/}
              done

              mkdir -p /run/sshd

              {{- with .Values.initscripts }}
              {{- range $key, $value := . }}
              /usr/share/initscripts/{{ $key }}
              {{- end }}
              {{- end }}

              /usr/sbin/sshd -D -e -E /proc/1/fd/1
          lifecycle: {{ .Values.lifecycle | toJson }}
          resources: {{ .Values.resources | toJson }}
          ports:
            - name: ssh
              containerPort: 1022
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/users
          - name: usr-share-initscripts
            mountPath: /usr/share/initscripts
          {{- range $key, $value := .Values.ssh }}
          - name: sshd-configs
            mountPath: /etc/ssh/{{ $key }}
            subPath: {{ $key }}
          {{- end }}
          - name: {{ .Release.Name }}-rsa
            mountPath: /etc/ssh/ssh_host_rsa_key
            subPath: ssh_host_rsa_key
          - name: {{ .Release.Name }}-ecdsa
            mountPath: /etc/ssh/ssh_host_ecdsa_key
            subPath: ssh_host_ecdsa_key
          - name: {{ .Release.Name }}-ed25519
            mountPath: /etc/ssh/ssh_host_ed25519_key
            subPath: ssh_host_ed25519_key
          - name: {{ .Release.Name }}-rsa
            mountPath: /etc/ssh/ssh_host_rsa_key.pub
            subPath: ssh_host_rsa_key.pub
          - name: {{ .Release.Name }}-ecdsa
            mountPath: /etc/ssh/ssh_host_ecdsa_key.pub
            subPath: ssh_host_ecdsa_key.pub
          - name: {{ .Release.Name }}-ed25519
            mountPath: /etc/ssh/ssh_host_ed25519_key.pub
            subPath: ssh_host_ed25519_key.pub
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.dnsConfig }}
      dnsConfig: {{ . | toJson }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      affinity: {{ .Values.affinity | toJson }}
      imagePullSecrets: {{ .Values.image.imagePullSecrets | toJson }}
{{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
{{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}
      - name: sshd-configs
        configMap:
          name: {{ .Release.Name }}-etc-ssh
          defaultMode: 0600
      - name: usr-share-initscripts
        configMap:
          name: {{ .Release.Name }}-usr-share-initscripts
          defaultMode: 0755
      - name: {{ .Release.Name }}-dsa
        secret:
          secretName: {{ .Release.Name }}-dsa
          defaultMode: 0600
      - name: {{ .Release.Name }}-rsa
        secret:
          secretName: {{ .Release.Name }}-rsa
          defaultMode: 0600
      - name: {{ .Release.Name }}-ecdsa
        secret:
          secretName: {{ .Release.Name }}-ecdsa
          defaultMode: 0600
      - name: {{ .Release.Name }}-ed25519
        secret:
          secretName: {{ .Release.Name }}-ed25519
          defaultMode: 0600
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
{{ toYaml .Values.users | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-etc-ssh
data:
{{ tpl (toYaml .Values.ssh) $ | indent 2 }}

---
# Additional startup commands
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-usr-share-initscripts
data:
{{ tpl (toYaml .Values.initscripts) $ | indent 2 }}
